
key1: v1
key2: v2
key3: v3

eureka:
  client:
    service-url:
      defaultZone: http://peer1:9003/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
